[package]
name = "lpl-example-custom-heap"
version = "1.0.0"
description = "Lumos Program Library Custom Heap Example"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
default = ["custom-heap"]
custom-heap = []
no-entrypoint = []
test-sbf = []

[dependencies]
lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
