[package]
name = "lpl-example-transfer-lamports"
version = "1.0.0"
description = "Lumos Program Library Transfer Lamports Example"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
