[package]
name = "lpl-token-confidential-transfer-ciphertext-arithmetic"
version = "0.1.0"
description = "Lumos Program Library Confidential Transfer Ciphertext Arithmetic"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = { workspace = true }

bytemuck = { workspace = true }

curve25519-dalek = { workspace = true }
lumos-zk-token-sdk = { workspace = true }

[dev-dependencies]
lpl-token-confidential-transfer-proof-generation = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
