[package]
name = "lpl-type-length-value-derive-test"
version = "0.1.0"
description = "Testing Derive Macro Library for SPL Type Length Value traits"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
borsh = "1.5.1"
lumos-program = { workspace = true }
lpl-discriminator = { version = "0.3.0", path = "../discriminator" }
lpl-type-length-value = { version = "0.5.0", path = "../type-length-value", features = [
  "derive",
] }
