[package]
name = "lpl-token-2022"
version = "4.0.1"
description = "Lumos Program Library Token 2022"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[dependencies]
arrayref = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
base64 = { workspace = true }

lazy_static = { workspace = true }
proptest = { workspace = true }
serial_test = { workspace = true }
serde_json = { workspace = true }

bytemuck = { workspace = true }
security-txt = { workspace = true }

lumos-program = { workspace = true }
#lumos-transaction-status = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lumos-zk-token-sdk = { workspace = true }

lpl-memo = { workspace = true }
#lpl-token = { workspace = true }
lpl-token-group-interface = { workspace = true }
lpl-token-metadata-interface = { workspace = true }
lpl-transfer-hook-interface = { workspace = true }
lpl-type-length-value = { workspace = true }
lpl-pod = { workspace = true }
lpl-tlv-account-resolution = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

