[package]
name = "lpl-token-upgrade-cli"
version = "0.1.1"
description = "SPL Token Upgrade Command-line Utility"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = { workspace = true }
futures-util = { workspace = true }

tokio = { workspace = true }

lumos-clap-v3-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-client = { workspace = true }
lumos-logger = { workspace = true }
lumos-remote-wallet = { workspace = true }
lumos-sdk = { workspace = true }
#lumos-test-validator = { workspace = true }

lpl-associated-token-account = { workspace = true }
lpl-token = { workspace = true }
lpl-token-2022 = { workspace = true }
lpl-token-client = { workspace = true }
lpl-token-upgrade = { workspace = true }

[[bin]]
name = "lpl-token-upgrade"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
