[package]
name = "lpl-feature-proposal-cli"
version = "1.2.0"
description = "SPL Feature Proposal Command-line Utility"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }

lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-client = { workspace = true }
lumos-logger = { workspace = true }
lumos-sdk = { workspace = true }
lpl-feature-proposal = { workspace = true }

[[bin]]
name = "lpl-feature-proposal"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
