[package]
name = "lpl-tlv-account-resolution"
version = "0.7.0"
description = "Lumos Program Library TLV Account Resolution Interface"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
futures =  { workspace = true }
futures-util =  { workspace = true }

bytemuck = { workspace = true }

lumos-program = { workspace = true }
#lumos-client = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

lpl-discriminator = { workspace = true }
lpl-program-error = { workspace = true }
lpl-pod = { workspace = true }
lpl-type-length-value = { workspace = true }
#lpl-tlv-account-resolution = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
